java.sql.SQLException: Access denied for user 'root'@'localhost'
I am determined to find the reason the jvm is not able to connect to the
sql database.